import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Signupheader from "./header/signup-header";
import Header from "./header/header";
import Footer from "./footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container max-w-full bg-[#245D30] ">
          <Signupheader />
        </div>
        <div className="container max-w-full">
          <Header />
        </div>
        <div className="max-w-[1440px] w-full container mx-auto ">{children}</div>
        <div className="container max-w-full bg-[#245D30]">
          < Footer/>
        </div>
      </body>

    </html>
  );
}
